_target_: kwja.datamodule.datasets.word_dataset.WordDataset
model_name_or_path: ${model.model_name_or_path}
max_seq_length: ${model.max_seq_length}
tokenizer_kwargs: ${dataset.tokenizer_kwargs}
special_tokens: ${dataset.special_tokens}
restrict_cohesion_target: ${restrict_cohesion_target}
pas_cases: ${pas_cases}
bar_rels: ${bar_rels}
exophora_referents: ${exophora_referents}
cohesion_tasks: ${cohesion_tasks}
reading_resource_path: ${dataset.reading_resource_path}
document_split_stride: ${document_split_stride}
