prediction_writer:
  _target_: kwja.callbacks.word_module_writer.WordModuleWriter
  output_dir: ${run_dir}
  reading_resource_path: ${dataset.reading_resource_path}
  pred_filename: "predict"
  jumandic_path: ${oc.env:DATA_DIR}/jumandic
  ambig_surf_specs: [
    {
      conjtype: "イ形容詞アウオ段",
      conjform: "エ基本形",
    },
    {
      conjtype: "イ形容詞イ段",
      conjform: "エ基本形",
    },
    {
      conjtype: "イ形容詞イ段特殊",
      conjform: "エ基本形",
    },
  ]
