defaults:
  - base
  - callbacks: [early_stopping, model_checkpoint, model_summary, senter_module_writer, progress_bar]
  - datamodule: senter
  - logger: null
  - encoder: char_deberta_tiny
  - module: senter
  - optimizer: adamw
  - scheduler: constant_schedule_with_warmup
  - trainer: debug
  - _self_

max_seq_length: 256
do_predict_after_train: true
checkpoint_path: ""
document_split_stride: -1

# set monitor and mode for early_stopping and model_checkpoint
monitor: valid/aggregated_senter_metrics
mode: max
aggregating_metrics:
  - sent_segmentation_f1

# hyper-parameters to be tuned
lr: 2e-5
max_epochs: 2
warmup_steps: 10
effective_batch_size: 16

# environment dependent settings
devices: ${oc.env:DEVICES,1}
max_batches_per_device: ${oc.env:MAX_BATCHES_PER_DEVICE,2}
num_workers: ${oc.env:NUM_WORKERS,0}
compile: ${oc.env:COMPILE,false}

ignore_hparams_on_save: false

# constants
hparams_to_ignore_on_save: []
