defaults:
  - train:
    - seq2seq_kyoto.yaml
    - seq2seq_kyoto_ed.yaml
    - seq2seq_kwdlc.yaml
    - seq2seq_fuman.yaml
    - seq2seq_wac.yaml
    - seq2seq_norm.yaml
  - valid:
    - seq2seq_kyoto.yaml
    - seq2seq_kwdlc.yaml
    - seq2seq_fuman.yaml
    - seq2seq_wac.yaml
    - seq2seq_norm.yaml
  - test:
    - seq2seq_kyoto.yaml
    - seq2seq_kwdlc.yaml
    - seq2seq_fuman.yaml
    - seq2seq_wac.yaml
    - seq2seq_norm.yaml
    - seq2seq_canon.yaml
  - predict:
    - seq2seq_inference.yaml

batch_size: ${max_batches_per_device}
num_workers: ${num_workers}
dataset_type: seq2seq
